# LISTAR Auth:
GET http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY0MjYzOTk5OCwiZXhwIjoxNjQyNjQwMDU4fQ.-W8RtEB7i8ZksSl-pnAPw-RLTYVohgozAa4jCDTV9Qo
###

# CADASTRAR Auth:
POST http://localhost:3000/auth
Content-Type: application/json

{
"email":"admin@admin.com",
"senha":"admin"   
}
###

