# LISTAR TODOS Seguindo:
GET http://localhost:3000/seguindo
###

# LISTAR UM seguindo por ID:
GET http://localhost:3000/seguindo/1
###

# CADASTRAR um novo seguindo:
POST http://localhost:3000/seguindo
Content-Type: application/json

{
    "nome":"STRING",
    "usuarioid": NUMBER
}
###

# EXCLUIR seguidor por ID:
DELETE http://localhost:3000/seguidores/1
###