# LISTAR TODOS tweets:
GET http://localhost:3000/tweets
###

# LISTAR UM tweet por ID:
GET http://localhost:3000/tweets/1
###

# CADASTRAR um novo tweet:
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "texto":"STRING",
    "usuarioid": NUMBER
}
###

# EXCLUIR tweet por ID:
DELETE http://localhost:3000/tweets/1
###