# LISTAR TODOS usuários:
GET http://localhost:3000/usuarios
###

# LISTAR UM usuário por ID:
GET http://localhost:3000/usuarios/3
###

# CADASTRAR um novo usuário:
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"STRING",
    "sobrenome":"STRING",
    "email":"STRING",
    "senha":"STRING",
    "sobre":"STRING",
    "nascimento":"STRING"    
}
###

# ALTERAR um usuário por ID:
# Observações: no PATCH pode ser alterado apenas 1 campo ou todos eles.
PATCH  http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome":"STRING",
    "sobrenome":"STRING",
    "email":"STRING",
    "senha":"STRING",
    "sobre":"STRING",
    "nascimento":"STRING"    
}
###

# EXCLUIR usuário por ID:
DELETE http://localhost:3000/usuarios/7
###